[env:ai-thinker-cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
  -D BOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue

