[platformio]
default_envs = xiao-esp32s3-sense

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:xiao-esp32s3-sense]
board = seeed_xiao_esp32s3
board_build.partitions = default_8MB.csv
build_flags =
  -D BOARD_HAS_PSRAM
  -D RISK_ZERO_CAMERA_XIAO_ESP32S3

[env:ai-thinker-cam]
board = esp32cam
board_build.partitions = huge_app.csv
build_flags =
  -D BOARD_HAS_PSRAM
  -D RISK_ZERO_CAMERA_AI_THINKER
  -mfix-esp32-psram-cache-issue

