#pragma once

#include "xparameters.h"

#define RISK_ZERO_DEVICE_ID "ARTY-A7-100T-01"
#define RISK_ZERO_UDP_PORT 5005
#define RISK_ZERO_HTTP_PORT 80
#define RISK_ZERO_FRAME_WIDTH 160
#define RISK_ZERO_FRAME_HEIGHT 120
#define RISK_ZERO_FRAME_BYTES (RISK_ZERO_FRAME_WIDTH * RISK_ZERO_FRAME_HEIGHT)
#define RISK_ZERO_MOTION_THRESHOLD 24
#define RISK_ZERO_MIN_MOTION_PIXELS 80
#define RISK_ZERO_TRACK_MISSING_FRAMES 3
#define RISK_ZERO_IP_A 192
#define RISK_ZERO_IP_B 168
#define RISK_ZERO_IP_C 0
#define RISK_ZERO_IP_D 40
#define RISK_ZERO_GATEWAY_D 1

/*
 * Vivado block design에서 생성된 실제 인스턴스 이름과 다르면 이 한 줄만
 * 수정한다. IP 이름을 risk_zero_motion_axi_lite_0으로 두면 보통 아래 이름이
 * 생성된다.
 */
#ifndef RISK_ZERO_MOTION_BASEADDR
#if defined(XPAR_RISK_ZERO_MOTION_0_BASEADDR)
#define RISK_ZERO_MOTION_BASEADDR XPAR_RISK_ZERO_MOTION_0_BASEADDR
#elif defined(XPAR_RISK_ZERO_MOTION_0_S_AXI_BASEADDR)
#define RISK_ZERO_MOTION_BASEADDR XPAR_RISK_ZERO_MOTION_0_S_AXI_BASEADDR
#elif defined(XPAR_RISK_ZERO_MOTION_AXI_LITE_0_S_AXI_BASEADDR)
#define RISK_ZERO_MOTION_BASEADDR XPAR_RISK_ZERO_MOTION_AXI_LITE_0_S_AXI_BASEADDR
#elif defined(XPAR_RISK_ZERO_MOTION_AXI_LITE_0_BASEADDR)
#define RISK_ZERO_MOTION_BASEADDR XPAR_RISK_ZERO_MOTION_AXI_LITE_0_BASEADDR
#else
#error "Set RISK_ZERO_MOTION_BASEADDR to the motion IP base address in xparameters.h"
#endif
#endif

#ifndef RISK_ZERO_EMAC_BASEADDR
#if defined(XPAR_AXI_ETHERNETLITE_0_BASEADDR)
#define RISK_ZERO_EMAC_BASEADDR XPAR_AXI_ETHERNETLITE_0_BASEADDR
#elif defined(XPAR_AXI_ETHERNET_LITE_0_BASEADDR)
#define RISK_ZERO_EMAC_BASEADDR XPAR_AXI_ETHERNET_LITE_0_BASEADDR
#else
#error "Set RISK_ZERO_EMAC_BASEADDR to the AXI Ethernet Lite base address"
#endif
#endif
